export type CampaignFundingTipInput = {
  businessArea?: string;
  businessSubarea?: string;
  businessStage?: string;
  businessType?: string;
};

export function inferCampaignFundingTip({ businessArea, businessSubarea, businessStage, businessType }: CampaignFundingTipInput): string | null {
  console.log(businessArea, businessSubarea, businessStage, businessType);
  if (!businessArea || !businessStage || !businessType) return null;

  const normalize = (str: string) => str.toLowerCase();
  const is = (val: string, set: string[]) => set.includes(val);

  const statusBC = ["CONCEPT", "MVP"];
  const statusDF = ["VALIDATED", "PIVOTING"];

  const areaMatches = (target: string) => normalize(businessArea).includes(normalize(target));
  const subMatches = (target: string) => businessSubarea && normalize(businessSubarea).includes(normalize(target));

  const businessTypeToLetterMap: Record<string, string> = {
    "PRODUCT": "a",
    "SERVICE": "b",
    "SUBSCRIPTION": "c",
    "PLATFORM": "d",
    "LICENSING": "e",
    "RENTAL": "f",
    "SHARING": "g",
    "ADVERTISING": "h",
    "IMPACT": "i",
  };

  const letter = businessTypeToLetterMap[businessType as keyof typeof businessTypeToLetterMap];
  if (!letter) return null;

  const fundingTips: Record<string, Record<string, string>> = {
    "1": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 30.000€ e 75.000€, usualmente aplicado em protótipos, maquinaria, patentes ou certificações. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 22.000€ e 54.000€, usualmente usado para validação do conceito ou certificações. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 28.000€ e 70.000€, usualmente usado para validação do conceito ou certificações. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 37.000€ e 90.000€, usualmente usado para validação do conceito ou certificações. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 32.000€ e 78.000€, usualmente aplicado em protótipos, maquinaria, patentes ou certificações. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 35.000€ e 84.000€, usualmente aplicado em aquisição de stock, tecnologia ou certificações. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 23.000€ e 57.000€. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 22.000€ e 54.000€. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 27.000€ e 66.000€, usualmente aplicado em protótipos, maquinaria, patentes ou certificações. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "2": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 75.000€ e 187.000€, usualmente aplicado em contratação de equipa ou investimento em maquinaria/tecnologia nova. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 54.000€ e 135.000€, usualmente aplicado em contratação de equipa ou investimento em tecnologia nova. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 70.000€ e 172.000€, usualmente aplicado em aquisição de ferramentas para escalar o negócio. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 90.000€ e 225.000€, usualmente aplicado em contratação de equipa ou investimento em tecnologia nova. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 78.000€ e 195.000€, usualmente aplicado em aquisição de ferramentas para escalar o negócio. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 84.000€ e 210.000€, usualmente aplicado em aquisição de ferramentas para escalar o negócio. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 57.000€ e 142.000€, usualmente aplicado em contratação de equipa ou investimento em maquinaria/tecnologia nova. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 54.000€ e 135.000€, usualmente aplicado em aquisição de ferramentas para escalar o negócio. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário está entre os 66.000€ e 165.000€, usualmente aplicado em contratação de equipa ou investimento em maquinaria/tecnologia nova. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "3": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 50.000€, e é habitualmente usado para cobrir custos de renda, mobiliário e obras, stock inicial e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 13.000€ e 36.000€, e é habitualmente usado para cobrir custos de renda, mobiliário, obras e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 17.000€ e 46.000€, e é habitualmente usado para cobrir custos de renda, mobiliário, obras e licenças.. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 19.000€ e 52.000€, e é habitualmente usado para cobrir custos de renda, mobiliário, obras, stock inicial e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 21.000€ e 56.000€, e é habitualmente usado para cobrir custos de renda, mobiliário, obras, stock inicial e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 14.000€ e 38.000€, e é habitualmente usado para cobrir custos de renda, mobiliário, obras, stock inicial e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 13.000€ e 36.000€, e é habitualmente usado para cobrir custos de renda, mobiliário, obras, stock inicial e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 16.000€ e 44.000€, e é habitualmente usado para cobrir custos de renda, mobiliário, obras, stock inicial e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "4": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 37.000€ e 100.000€, e é habitualmente usado para cobrir custos de expansão, renovação do espaço ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 27.000€ e 72.000€, e é habitualmente usado para cobrir custos de expansão, renovação do espaço ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 34.000€ e 92.000€, e é habitualmente usado para cobrir custos de expansão, renovação do espaço ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 39.000€ e 104.000€, e é habitualmente usado para cobrir custos de expansão, renovação do espaço ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 42.000€ e 112.000€, e é habitualmente usado para cobrir custos de expansão, renovação do espaço ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 28.000€ e 76.000€, e é habitualmente usado para cobrir custos de expansão, renovação do espaço ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 27.000€ e 72.000€, e é habitualmente usado para cobrir custos de expansão, renovação do espaço ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 33.000€ e 88.000€, e é habitualmente usado para cobrir custos de expansão, renovação do espaço ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "5": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 10.000€ e 25.000€, e é habitualmente usado para desenvolvimento da plataforma, marketing digital e logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 18.000€, e é habitualmente usado para desenvolvimento da plataforma, marketing digital e logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 23.000€, e é habitualmente usado para desenvolvimento da plataforma, marketing digital e logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 12.000€ e 30.000€, e é habitualmente usado para desenvolvimento da plataforma, marketing digital e logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 10.000€ e 26.000€, e é habitualmente usado para desenvolvimento da plataforma, marketing digital e logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 11.000€ e 28.000€, e é habitualmente usado para desenvolvimento da plataforma, marketing digital e logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 19.000€, e é habitualmente usado para desenvolvimento da plataforma, marketing digital e logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 18.000€, e é habitualmente usado para desenvolvimento da plataforma, marketing digital e logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 8.000€ e 22.000€, e é habitualmente usado para desenvolvimento da plataforma, marketing digital e logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "6": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 25.000€ e 75.000€, e é habitualmente usado para melhorias na plataforma, campanhas de marketing ou reforço da logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 54.000€, e é habitualmente usado para melhorias na plataforma, campanhas de marketing ou reforço da logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 23.000€ e 70.000€, e é habitualmente usado para melhorias na plataforma, campanhas de marketing ou reforço da logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 30.000€ e 90.000€, e é habitualmente usado para melhorias na plataforma, campanhas de marketing ou reforço da logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 26.000€ e 78.000€, e é habitualmente usado para melhorias na plataforma, campanhas de marketing ou reforço da logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 28.000€ e 84.000€, e é habitualmente usado para melhorias na plataforma, campanhas de marketing ou reforço da logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 19.000€ e 57.000€, e é habitualmente usado para melhorias na plataforma, campanhas de marketing ou reforço da logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 54.000€, e é habitualmente usado para melhorias na plataforma, campanhas de marketing ou reforço da logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 22.000€ e 66.000€, e é habitualmente usado para melhorias na plataforma, campanhas de marketing ou reforço da logística. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "7": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 25.000€ e 62.000€, e é habitualmente usado para cobrir a taxa de entrada, adaptação do espaço e formação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 45.000€, e é habitualmente usado para cobrir a taxa de entrada, adaptação do espaço e formação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 23.000€ e 57.000€, e é habitualmente usado para cobrir a taxa de entrada, adaptação do espaço e formação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 30.000€ e 75.000€, e é habitualmente usado para cobrir a taxa de entrada, desenvolvimento da plataforma e formação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 26.000€ e 65.000€, e é habitualmente usado para cobrir a taxa de entrada, adaptação do espaço e formação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 28.000€ e 70.000€, e é habitualmente usado para cobrir a taxa de entrada, adaptação do espaço e formação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 19.000€ e 47.000€, e é habitualmente usado para cobrir a taxa de entrada, adaptação do espaço e formação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 45.000€, e é habitualmente usado para cobrir a taxa de entrada, adaptação do espaço e formação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 22.000€ e 55.000€, e é habitualmente usado para cobrir a taxa de entrada, adaptação do espaço e formação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "8": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 62.000€ e 150.000€, e é habitualmente usado para cobrir custos de expansão e suporte. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 45.000€ e 108.000€, e é habitualmente usado para cobrir custos de expansão e suporte. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 57.000€ e 138.000€, e é habitualmente usado para cobrir custos de expansão e suporte. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 75.000€ e 180.000€. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 65.000€ e 156.000€, e é habitualmente usado para cobrir custos de expansão e suporte. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 70.000€ e 168.000€, e é habitualmente usado para cobrir custos de expansão e suporte. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 47.000€ e 114.000€, e é habitualmente usado para cobrir custos de expansão e suporte. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 45.000€ e 108.000€, e é habitualmente usado para cobrir custos de expansão e suporte. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 55.000€ e 132.000€, e é habitualmente usado para cobrir custos de expansão e suporte. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "9": {
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 27.000€, e é habitualmente usado para licenças, espaço ou materiais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 11.000€ e 34.000€, e é habitualmente usado para licenças, espaço ou materiais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 15.000€ e 45.000€, e é habitualmente usado para licenças, plataforma ou materiais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 13.000€ e 39.000€, e é habitualmente usado para licenças, espaço ou materiais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 14.000€ e 42.000€, e é habitualmente usado para licenças, espaço ou materiais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 28.000€, e é habitualmente usado para licenças, espaço ou materiais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 27.000€, e é habitualmente usado para licenças, espaço ou materiais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 11.000€ e 33.000€, e é habitualmente usado para licenças, espaço ou materiais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "10": {
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 27.000€ e 81.000€, e é habitualmente usado para contratação, certificações ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 34.000€ e 103.000€, e é habitualmente usado para contratação, certificações ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 45.000€ e 135.000€, e é habitualmente usado para contratação, certificações ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 39.000€ e 117.000€, e é habitualmente usado para contratação, certificações ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 42.000€ e 126.000€, e é habitualmente usado para contratação, certificações ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 28.000€ e 85.000€, e é habitualmente usado para contratação, certificações ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 27.000€ e 81.000€, e é habitualmente usado para contratação, certificações ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 33.000€ e 99.000€, e é habitualmente usado para contratação, certificações ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "11": {
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 13.000€ e 36.000€, e é habitualmente usado para aquisição de equipamentos ou hardware, desenvolvimento de software ou testes de integração. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 17.000€ e 46.000€, e é habitualmente usado para aquisição de equipamentos ou hardware, desenvolvimento de software ou testes de integração. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 22.000€ e 60.000€, e é habitualmente usado para aquisição de equipamentos ou hardware, desenvolvimento de software ou testes de integração. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 19.000€ e 52.000€, e é habitualmente usado para aquisição de equipamentos ou hardware, desenvolvimento de software ou testes de integração. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 21.000€ e 56.000€, e é habitualmente usado para aquisição de equipamentos ou hardware, desenvolvimento de software ou testes de integração. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 14.000€ e 38.000€, e é habitualmente usado para aquisição de equipamentos ou hardware, desenvolvimento de software ou testes de integração. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 13.000€ e 36.000€, e é habitualmente usado para aquisição de equipamentos ou hardware, desenvolvimento de software ou testes de integração. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 16.000€ e 44.000€, e é habitualmente usado para aquisição de equipamentos ou hardware, desenvolvimento de software ou testes de integração. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "12": {
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 36.000€ e 108.000€, e é habitualmente usado para reforço de infraestrutura, marketing ou parcerias. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 46.000€ e 138.000€, e é habitualmente usado para reforço de infraestrutura, marketing ou parcerias. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 60.000€ e 180.000€, e é habitualmente usado para reforço de infraestrutura, marketing ou parcerias. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 52.000€ e 156.000€, e é habitualmente usado para reforço de infraestrutura, marketing ou parcerias. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 56.000€ e 168.000€, e é habitualmente usado para reforço de infraestrutura, marketing ou parcerias. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 38.000€ e 114.000€, e é habitualmente usado para reforço de infraestrutura, marketing ou parcerias. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 36.000€ e 108.000€, e é habitualmente usado para reforço de infraestrutura, marketing ou parcerias. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 44.000€ e 132.000€, e é habitualmente usado para reforço de infraestrutura, marketing ou parcerias. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "13": {
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 22.000€, e é habitualmente usado para adquirir equipamentos, certificações ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 28.000€, e é habitualmente usado para adquirir equipamentos, certificações ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 12.000€ e 37.000€, e é habitualmente usado para desenvolvimento da plataforma, certificações ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 10.000€ e 32.000€, e é habitualmente usado para adquirir equipamentos, certificações ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 11.000€ e 35.000€, e é habitualmente usado para adquirir equipamentos, certificações ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 24.000€, e é habitualmente usado para adquirir equipamentos, certificações ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 22.000€, e é habitualmente usado para adquirir equipamentos, certificações ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 8.000€ e 27.000€, e é habitualmente usado para adquirir equipamentos, certificações ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "14": {
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 45.000€, e é habitualmente usado para contratação, certificações, software ou expansão. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 23.000€ e 57.000€, e é habitualmente usado para contratação, certificações, software ou expansão. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 30.000€ e 75.000€, e é habitualmente usado para contratação, certificações, software ou expansão. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 26.000€ e 65.000€, e é habitualmente usado para contratação, certificações, software ou expansão. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 28.000€ e 70.000€, e é habitualmente usado para contratação, certificações, software ou expansão. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 19.000€ e 47.000€, e é habitualmente usado para contratação, certificações, software ou expansão. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 45.000€, e é habitualmente usado para contratação, certificações, software ou expansão. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 22.000€ e 55.000€, e é habitualmente usado para contratação, certificações, software ou expansão. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },

    "15": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 37.000€ e 87.000€, e é habitualmente usado para licenças regulatórias, compliance e sistemas de segurança. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 27.000€ e 63.000€, e é habitualmente usado para licenças regulatórias, compliance e sistemas de segurança. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 34.000€ e 80.000€, e é habitualmente usado para licenças regulatórias, compliance e sistemas de segurança. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 45.000€ e 105.000€, e é habitualmente usado para licenças regulatórias, compliance e sistemas de segurança. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 39.000€ e 91.000€, e é habitualmente usado para licenças regulatórias, compliance e sistemas de segurança. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 42.000€ e 98.000€, e é habitualmente usado para licenças regulatórias, compliance e sistemas de segurança. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 28.000€ e 66.000€, e é habitualmente usado para licenças regulatórias, compliance e sistemas de segurança. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 27.000€ e 63.000€, e é habitualmente usado para licenças regulatórias, compliance e sistemas de segurança. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 33.000€ e 77.000€, e é habitualmente usado para licenças regulatórias, compliance e sistemas de segurança. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },

    "16": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 100.000€ e 250.000€, e é habitualmente usado para escalar operações ou cumprir com actualizações regulamentares. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 72.000€ e 180.000€, e é habitualmente usado para escalar operações ou cumprir com actualizações regulamentares. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 92.000€ e 230.000€, e é habitualmente usado para escalar operações ou cumprir com actualizações regulamentares. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 120.000€ e 300.000€, e é habitualmente usado para escalar operações ou cumprir com actualizações regulamentares. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 104.000€ e 260.000€, e é habitualmente usado para escalar operações ou cumprir com actualizações regulamentares. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 112.000€ e 280.000€, e é habitualmente usado para escalar operações ou cumprir com actualizações regulamentares. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 76.000€ e 190.000€, e é habitualmente usado para escalar operações ou cumprir com actualizações regulamentares. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 72.000€ e 180.000€, e é habitualmente usado para escalar operações ou cumprir com actualizações regulamentares. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 88.000€ e 220.000€, e é habitualmente usado para escalar operações ou cumprir com actualizações regulamentares. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },

    "17": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 50.000€ e 125.000€, e é habitualmente usado para desenvolvimento tecnológico, validação legal e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 36.000€ e 90.000€, e é habitualmente usado para desenvolvimento tecnológico, validação legal e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 46.000€ e 115.000€, e é habitualmente usado para desenvolvimento tecnológico, validação legal e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 60.000€ e 150.000€, e é habitualmente usado para desenvolvimento tecnológico, validação legal e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 52.000€ e 130.000€, e é habitualmente usado para desenvolvimento tecnológico, validação legal e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 56.000€ e 140.000€, e é habitualmente usado para desenvolvimento tecnológico, validação legal e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 38.000€ e 95.000€, e é habitualmente usado para desenvolvimento tecnológico, validação legal e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 36.000€ e 90.000€, e é habitualmente usado para desenvolvimento tecnológico, validação legal e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 44.000€ e 110.000€, e é habitualmente usado para desenvolvimento tecnológico, validação legal e licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "18": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 125.000€ e 375.000€, e é habitualmente usado para escalabilidade, compliance e integração com parceiros. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 90.000€ e 270.000€, e é habitualmente usado para escalabilidade, compliance e integração com parceiros. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 115.000€ e 345.000€, e é habitualmente usado para escalabilidade, compliance e integração com parceiros. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 150.000€ e 450.000€, e é habitualmente usado para escalabilidade, compliance e integração com parceiros. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 130.000€ e 390.000€, e é habitualmente usado para escalabilidade, compliance e integração com parceiros. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 140.000€ e 420.000€, e é habitualmente usado para escalabilidade, compliance e integração com parceiros. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 95.000€ e 285.000€, e é habitualmente usado para escalabilidade, compliance e integração com parceiros. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 90.000€ e 270.000€, e é habitualmente usado para escalabilidade, compliance e integração com parceiros. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 110.000€ e 330.000€, e é habitualmente usado para escalabilidade, compliance e integração com parceiros. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "19": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 25.000€ e 75.000€, e é habitualmente usado para protótipos, licenças ou equipamentos. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 54.000€, e é habitualmente usado para adaptações do espaço, licenças, equipamentos e contratação com fornecedores. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 23.000€ e 70.000€, e é habitualmente usado para adaptações do espaço, licenças, equipamentos e contratação com fornecedores. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 30.000€ e 90.000€, e é habitualmente usado para tecnologia, licenças e contratação com fornecedores. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 26.000€ e 78.000€, e é habitualmente usado para adaptações do espaço, licenças, equipamentos e contratação com fornecedores. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 28.000€ e 84.000€, e é habitualmente usado para adaptações do espaço, licenças, equipamentos e contratação com fornecedores. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 19.000€ e 57.000€, e é habitualmente usado para adaptações do espaço, licenças, equipamentos e contratação com fornecedores. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 54.000€, e é habitualmente usado para adaptações do espaço, licenças, equipamentos e contratação com fornecedores. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 22.000€ e 66.000€, e é habitualmente usado para adaptações do espaço, licenças, equipamentos e contratação com fornecedores. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "20": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 62.000€ e 187.000€, e é habitualmente usado para melhorias, contratação ou marketing. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 45.000€ e 135.000€, e é habitualmente usado para reformas, contratação ou campanhas de fidelização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 57.000€ e 172.000€, e é habitualmente usado para reformas, contratação ou campanhas de fidelização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 75.000€ e 225.000€, e é habitualmente usado para melhorias, contratação ou campanhas de fidelização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 65.000€ e 195.000€, e é habitualmente usado para reformas, contratação ou campanhas de fidelização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 70.000€ e 210.000€, e é habitualmente usado para reformas, contratação ou campanhas de fidelização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 47.000€ e 142.000€, e é habitualmente usado para reformas, contratação ou campanhas de fidelização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 45.000€ e 135.000€, e é habitualmente usado para reformas, contratação ou campanhas de fidelização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 55.000€ e 165.000€, e é habitualmente usado para reformas, contratação ou campanhas de fidelização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "21": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 12.000€ e 37.000€, e é habitualmente usado para software, branding, aquisição de clientes. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 27.000€, e é habitualmente usado para software, branding, aquisição de clientes. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 11.000€ e 34.000€, e é habitualmente usado para software, branding, aquisição de clientes. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 15.000€ e 45.000€, e é habitualmente usado para software, branding, aquisição de clientes. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 13.000€ e 40.000€, e é habitualmente usado para software, branding, aquisição de clientes. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 14.000€ e 42.000€, e é habitualmente usado para software, branding, aquisição de clientes. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 28.000€, e é habitualmente usado para software, branding, aquisição de clientes. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 27.000€, e é habitualmente usado para software, branding, aquisição de clientes. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 11.000€ e 33.000€, e é habitualmente usado para software, branding, aquisição de clientes. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "22": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 37.000€ e 100.000€, e é habitualmente usado para contratação de equipa ou de ferramentas de automação e expansão de canais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 27.000€ e 72.000€, e é habitualmente usado para contratação de equipa ou de ferramentas de automação e expansão de canais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 34.000€ e 92.000€, e é habitualmente usado para contratação de equipa ou de ferramentas de automação e expansão de canais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 45.000€ e 120.000€, e é habitualmente usado para contratação de equipa ou de ferramentas de automação e expansão de canais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 39.000€ e 104.000€, e é habitualmente usado para contratação de equipa ou de ferramentas de automação e expansão de canais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 42.000€ e 112.000€, e é habitualmente usado para contratação de equipa ou de ferramentas de automação e expansão de canais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 28.000€ e 76.000€, e é habitualmente usado para contratação de equipa ou de ferramentas de automação e expansão de canais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 27.000€ e 72.000€, e é habitualmente usado para contratação de equipa ou de ferramentas de automação e expansão de canais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 33.000€ e 88.000€, e é habitualmente usado para contratação de equipa ou de ferramentas de automação e expansão de canais. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "23": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 62.000€, e é habitualmente usado para equipamentos/hardware, edição ou licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 13.000€ e 45.000€, e é habitualmente usado para equipamentos/hardware, edição ou licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 17.000€ e 57.000€, e é habitualmente usado para equipamentos/hardware, edição ou licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 22.000€ e 75.000€, e é habitualmente usado para equipamentos/hardware, edição ou licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 19.000€ e 65.000€, e é habitualmente usado para equipamentos/hardware, edição ou licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 21.000€ e 70.000€, e é habitualmente usado para equipamentos/hardware, edição ou licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 14.000€ e 47.000€, e é habitualmente usado para equipamentos/hardware, edição ou licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 13.000€ e 45.000€, e é habitualmente usado para equipamentos/hardware, edição ou licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 16.000€ e 55.000€, e é habitualmente usado para equipamentos/hardware, edição ou licenças. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "24": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 62.000€ e 187.000€, e é habitualmente usado para escalar a produção. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 45.000€ e 135.000€, e é habitualmente usado para escalar a produção. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 57.000€ e 172.000€, e é habitualmente usado para escalar a produção. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 75.000€ e 225.000€, e é habitualmente usado para escalar a produção. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 65.000€ e 195.000€, e é habitualmente usado para escalar a produção. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 70.000€ e 210.000€, e é habitualmente usado para escalar a produção. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 47.000€ e 142.000€, e é habitualmente usado para escalar a produção. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 45.000€ e 135.000€, e é habitualmente usado para escalar a produção. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      i: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 55.000€ e 165.000€, e é habitualmente usado para escalar a produção. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "25": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 6.000€ e 25.000€, e é habitualmente usado para materiais, espaços de ensaio ou divulgação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 4.000€ e 18.000€, e é habitualmente usado para materiais, espaços de ensaio ou divulgação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 5.000€ e 23.000€, e é habitualmente usado para materiais, espaços de ensaio ou divulgação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 30.000€, e é habitualmente usado para materiais, espaços de ensaio ou divulgação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 6.000€ e 26.000€, e é habitualmente usado para materiais, espaços de ensaio ou divulgação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 28.000€, e é habitualmente usado para materiais, espaços de ensaio ou divulgação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 4.000€ e 19.000€, e é habitualmente usado para materiais, espaços de ensaio ou divulgação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 4.000€ e 18.000€, e é habitualmente usado para materiais, espaços de ensaio ou divulgação. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "26": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 25.000€ e 75.000€, e é habitualmente usado para tournées, exposições, internacionalização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 54.000€, e é habitualmente usado para tournées, exposições, internacionalização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 23.000€ e 69.000€, e é habitualmente usado para tournées, exposições, internacionalização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 30.000€ e 90.000€, e é habitualmente usado para tournées, exposições, internacionalização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 26.000€ e 78.000€, e é habitualmente usado para tournées, exposições, internacionalização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 28.000€ e 84.000€, e é habitualmente usado para tournées, exposições, internacionalização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 19.000€ e 57.000€, e é habitualmente usado para tournées, exposições, internacionalização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 18.000€ e 54.000€, e é habitualmente usado para tournées, exposições, internacionalização. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "27": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 12.000€ e 37.000€, e é habitualmente usado para digitalização, divulgação, curadoria ou exposições-piloto. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 27.000€, e é habitualmente usado para digitalização, divulgação, curadoria ou exposições-piloto. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 11.000€ e 34.000€, e é habitualmente usado para digitalização, divulgação, curadoria ou exposições-piloto. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 15.000€ e 45.000€, e é habitualmente usado para digitalização, divulgação, curadoria ou exposições-piloto. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 13.000€ e 39.000€, e é habitualmente usado para digitalização, divulgação, curadoria ou exposições-piloto. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 14.000€ e 42.000€, e é habitualmente usado para digitalização, divulgação, curadoria ou exposições-piloto. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 28.000€, e é habitualmente usado para digitalização, divulgação, curadoria ou exposições-piloto. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 27.000€, e é habitualmente usado para digitalização, divulgação, curadoria ou exposições-piloto. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "28": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 37.000€ e 125.000€, e é habitualmente usado para digitalização, conservação ou acessibilidade. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 27.000€ e 90.000€, e é habitualmente usado para digitalização, conservação ou acessibilidade. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 34.000€ e 115.000€, e é habitualmente usado para digitalização, conservação ou acessibilidade. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 45.000€ e 150.000€, e é habitualmente usado para digitalização, conservação ou acessibilidade. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 39.000€ e 130.000€, e é habitualmente usado para digitalização, conservação ou acessibilidade. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 42.000€ e 140.000€, e é habitualmente usado para digitalização, conservação ou acessibilidade. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 28.000€ e 95.000€, e é habitualmente usado para digitalização, conservação ou acessibilidade. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 27.000€ e 90.000€, e é habitualmente usado para digitalização, conservação ou acessibilidade. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "29": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 10.000€ e 31.000€, e é habitualmente usado para protótipos, custos de representação/divulgação ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 22.000€, e é habitualmente usado para protótipos, custos de representação/divulgação ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 9.000€ e 29.000€, e é habitualmente usado para protótipos, custos de representação/divulgação ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 12.000€ e 37.000€, e é habitualmente usado para protótipos, custos de representação/divulgação ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 10.000€ e 32.000€, e é habitualmente usado para protótipos, custos de representação/divulgação ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 11.000€ e 35.000€, e é habitualmente usado para protótipos, custos de representação/divulgação ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 24.000€, e é habitualmente usado para protótipos, custos de representação/divulgação ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 7.000€ e 22.000€, e é habitualmente usado para protótipos, custos de representação/divulgação ou tecnologia. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
    "30": {
      a: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 31.000€ e 100.000€, e é habitualmente usado para escalar a produção, proteger a propriedade intelectual ou internacionalizar. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      b: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 22.000€ e 72.000€, e é habitualmente usado para escalar, proteger a propriedade intelectual ou internacionalizar. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      c: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 29.000€ e 92.000€, e é habitualmente usado para escalar a produção, proteger a propriedade intelectual ou internacionalizar. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      d: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 37.000€ e 120.000€, e é habitualmente usado para escalar a produção, proteger a propriedade intelectual ou internacionalizar. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      e: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 32.000€ e 104.000€, e é habitualmente usado para escalar a produção, proteger a propriedade intelectual ou internacionalizar. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      f: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 35.000€ e 112.000€, e é habitualmente usado para escalar a produção, proteger a propriedade intelectual ou internacionalizar. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      g: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 23.000€ e 76.000€, e é habitualmente usado para escalar a produção, proteger a propriedade intelectual ou internacionalizar. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
      h: "Para o tipo de negócio mencionado, o financiamento médio necessário usualmente está entre os 22.000€ e 72.000€, e é habitualmente usado para escalar a produção, proteger a propriedade intelectual ou internacionalizar. Tem obviamente em conta todos os capitais próprios que tiveres ou outras fontes de financiamento que ajudem a cobrir os custos totais.",
    },
  };

  const matchOption = (): string | null => {
    if (areaMatches("INDUSTRY")) {
      if (is(businessStage, statusBC)) return "1";
      if (is(businessStage, statusDF)) return "2";
    }
    if (areaMatches("COMMERCE") && subMatches("RETAIL")) {
      if (is(businessStage, statusBC)) return "3";
      if (is(businessStage, statusDF)) return "4";
    }
    if (areaMatches("COMMERCE") && subMatches("WHOLESALE")) {
      if (is(businessStage, statusBC)) return "5";
      if (is(businessStage, statusDF)) return "6";
    }
    if (areaMatches("COMMERCE") && subMatches("FRANCHISE")) {
      if (is(businessStage, statusBC)) return "7";
      if (is(businessStage, statusDF)) return "8";
    }
    if (
      areaMatches("SERVICES") &&
      (subMatches("HEALTH_WELLNESS") || subMatches("EDUCATION") || subMatches("CONSULTING") || subMatches("LEGAL"))
    ) {
      if (is(businessStage, statusBC)) return "9";
      if (is(businessStage, statusDF)) return "10";
    }
    if (
      areaMatches("SERVICES") &&
      (subMatches("TECHNOLOGY") || subMatches("LOGISTICS"))
    ) {
      if (is(businessStage, statusBC)) return "11";
      if (is(businessStage, statusDF)) return "12";
    }
    if (areaMatches("SERVICES") && subMatches("SPECIALIZED")) {
      if (is(businessStage, statusBC)) return "13";
      if (is(businessStage, statusDF)) return "14";
    }
    if (areaMatches("FINANCE") && subMatches("BANKING")) {
      if (is(businessStage, statusBC)) return "15";
      if (is(businessStage, statusDF)) return "16";
    }
    if (areaMatches("FINANCE") && (subMatches("FINTECH") || subMatches("STOCK_MARKET"))) {
      if (is(businessStage, statusBC)) return "17";
      if (is(businessStage, statusDF)) return "18";
    }
    if (areaMatches("TOURISM")) {
      if (is(businessStage, statusBC)) return "19";
      if (is(businessStage, statusDF)) return "20";
    }
    if (
      areaMatches("MEDIA") &&
      (subMatches("ADVERTISING") || subMatches("JOURNALISM") || subMatches("INFO_MANAGEMENT") || subMatches("PR"))
    ) {
      if (is(businessStage, statusBC)) return "21";
      if (is(businessStage, statusDF)) return "22";
    }
    if (
      areaMatches("MEDIA") &&
      (subMatches("DIGITAL_PLATFORMS") || subMatches("AUDIOVISUAL"))
    ) {
      if (is(businessStage, statusBC)) return "23";
      if (is(businessStage, statusDF)) return "24";
    }
    if (areaMatches("CULTURE") && subMatches("ART_PRODUCTION")) {
      if (is(businessStage, statusBC)) return "25";
      if (is(businessStage, statusDF)) return "26";
    }
    if (areaMatches("CULTURE") && subMatches("HERITAGE")) {
      if (is(businessStage, statusBC)) return "27";
      if (is(businessStage, statusDF)) return "28";
    }
    if (areaMatches("CULTURE") && subMatches("CREATIVE_INDUSTRY")) {
      if (is(businessStage, statusBC)) return "29";
      if (is(businessStage, statusDF)) return "30";
    }
    return null;
  };

  const op = matchOption();
  if (!op || !fundingTips[op]?.[letter]) return null;

  return fundingTips[op]?.[letter];
}