export const campaignData = {
  id: "abcde",
  userId: "efghi",
  name: "Cocoa Haven – The Chocolate Café",
  businessType: "Service",
  businessArea: "Services",
  businessSubarea: "Food and beverage",
  businessStage: "Idea",
  description: "Cocoa Haven is more than a café — it's a sanctuary for chocolate lovers. Our dream is to create a warm, inviting space where every treat celebrates the world's favorite comfort ingredient: chocolate. From handcrafted hot chocolates to mousse cakes, truffles, and cocoa-infused drinks, everything on our menu is designed to delight the senses and spark joy. Whether you're meeting a friend, celebrating a small victory, or just need to turn a bad day into a good one, Cocoa Haven is the place to be. We source our chocolate from sustainable, fair-trade producers and focus on quality ingredients and friendly service. With your help, we'll bring this chocolate paradise to life in the heart of the city — where the smell of cocoa fills the air and happiness is served by the spoonful.",
  targetValue: 50000,
  modelType: "B2C",
  capitalPlan: "Funds will go toward securing the location, interior design (think cozy, warm tones and chocolatey décor), professional kitchen equipment, and initial marketing campaigns to attract our first community of chocolate lovers.",
  repaymentPeriod: 12,
  repaymentUnit: "Months",
  paymentFrequency: "Monthly",
  gracePeriod: 3,
  interestType: "Fixed",
  interestRate: 1.5,
  euriborIndexed: true,
  status: "DRAFT",
  investments: [
    {
      id: "1",
      amount: 9500,
      user: {
        id: "1",
        name: "Henrique Araújo",
        nif: "1012131415",
        identificationDocType: "CC",
        identificationDocNumber: "1012131415",
        docExpiry: "2026-01-01",
        address: "Rua das Flores, 1",
        postalCode: "1234-567",
        iban: "PT50 0001 2345 6789 0123 4567 890",
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "2",
      amount: 7000,
      user: {
        id: "2",
        name: "Susana Bastos",
        nif: "2021222324",
        identificationDocType: "CC",
        identificationDocNumber: "2021222324",
        docExpiry: "2026-01-01",
        address: "Rua das Oliveiras, 2",
        postalCode: "1234-567",
        iban: "PT50 0001 2345 6789 0123 4567 890",
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
};

export const userData = {
  id: "efghi",
  name: "Flora",
  surnames: "Oliveira",
  email: "flora.oliveira@example.com",
  password: "password",
  confirmPassword: "password",
  nif: "1234567890",
  identificationDocType: "CC",
  identificationDocNumber: "1234567890",
  docExpiry: "2026-01-01",
  address: "Rua da Praia, 123",
  postalCode: "1234-567",
  iban: "PT50 0001 2345 6789 0123 4567 890",
};